framework:
    messenger:
        serializer:
            default_serializer: App\Messenger\MessengerSerializer
        transports:
            match.api.to.match: '%env(Match)%'
        routing:
            'stdClass': match.api.to.match
